TLV: add support of TLV 202 ( RDKB-4347 OFW-3458 )
reference : gwprovapp implementatio of VendorSpecific TLV for setting DataModelObjects (TLV202.43.12)

Note : Some of the hunk that are not related to TLVs are not part of original commit. Needs to review them.

BUG DESCRIPTION:
	Added feature to support vendor-specific TLV to CM Config file that allows a DataModel Object to be set (TLV202.43.12).
	Format of this TLV202.43.12 is: <parameter>|<type>|<value>.
	Also includes changes for TLV202.2 for TR069 settings like EnableCWMP, URL parameters using config file

FIX DESCRIPTION:
    Implemented the new feature in gwprovapp.

TESTING PERFORMED:
    Verified DataModel objects can be set from config file using
    TLV202.43.12 (using PacketACE to generate the file).

Signed-off-by: Sai Charan <ssirpa.contractor@libertyglobal.com>

misc cleanup + compiler warning fixes ( * WIP * )

Try to reduce unnecessary dependencies on legacy TI data types, etc.

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

misc code cleanup ( drop unnecessary buffer zeroing, etc, etc )

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

fix ARM and ATOM date are not aligned ( OFW-795 )

Updating ATOM date after DOCSIS link-up event.

drop stray #include <sys_types.h>

All necessary types etc should be defined from gw_prov_abstraction.h

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

- cleanup the unused code for url in WriteTr69TlvData
- change the component name COMP_NAME_GW from GWPROV to CM.
- replace GWPROV_PRINT function to CcspTraceInfo function to remove the build error
- remove _PLATFORM_RASPBERRYPI_ and _COSA_BCM_ARM_flag from gw_prov_abstraction.h
  and don't remove typedefs(i.e Uint64/Int32/String etc) to remove build error.
- Some of the hunk that are not related to TLVs are not commited from below original commit. Needs to review them.

Signed-off-by: Jyoti <jjyoti@libertyglobal.com>

fix misuse of v_secure_system()

 | In file included from ../../../git/source/CMAgentSsp/gw_prov_sm.c:74:
 | ../../../git/source/CMAgentSsp/gw_prov_sm.c: In function 'WriteTr69TlvData':
 | ../../../git/source/CMAgentSsp/gw_prov_sm.c:676:37: error: format not a string literal and no format arguments [-Werror=format-security]
 |   676 |                     v_secure_system(cmd);
 |       |                                     ^~~

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>